### PR TITLE
More Esperanto translations

### PR DESCRIPTION
**Pull request by AetherSeed**

### CODE REVIEW

**Comment by djuretic** [comment]
Dankon :)

**Comment by contextis4kings** [comment]
@AetherSeed Question: are you still using this username?

**Comment by AetherSeed** [comment]
> @AetherSeed Question: are you still using this username?

Yes, though I don't use this site much.

**Comment by contextis4kings** [comment]
> > @AetherSeed Question: are you still using this username?
> 
> Yes, though I don't use this site much.

Okay. Thanks for the quick reply! I was surprised to see it taken as I use it everywhere else. Lol.

**Pull request merged**
